In [1]:
import f3dasm
import numpy as np

In [2]:
d = 3
function = f3dasm.functions.Levy(dimensionality=d, scale_bounds=np.tile([-1.,1.], (d,1)))

In [6]:
xx = np.array([[0.,1.,0.3], [0.2,0.4,0.7], [0.13,0.0,0.12]])
xx

array([[0.  , 1.  , 0.3 ],
       [0.2 , 0.4 , 0.7 ],
       [0.13, 0.  , 0.12]])

In [7]:
x = function.get_global_minimum(d)[0]
x

array([[0.70547865, 0.25385984, 0.65046922]])

In [13]:
function(xx)

array([48.74663132,  3.69937824, 12.23188471])

In [28]:
def new_func(x):
    y = []
    for xi in x:
        y.append(function(xi))

    return np.array(y).ravel()

In [29]:
(new_func(x) == function(x)).all()

True

In [5]:
axis = 1
out = np.zeros(shape=x.shape)
for a in x:
    Ni, Nk = a.shape[:axis], a.shape[axis+1:]
    for ii in np.ndindex(Ni):
        for kk in np.ndindex(Nk):
            f = function.evaluate(x[ii + np.s_[:,] + kk])
            Nj = f.shape
            for jj in np.ndindex(Nj):
                out[ii + jj + kk] = f[jj]

IndexError: index 1 is out of bounds for axis 0 with size 1