In [1]:
import f3dasm
import numpy as np
import tensorflow as tf

2023-02-28 13:18:30.544391: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-28 13:18:30.683947: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-28 13:18:31.312584: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.1/lib64:/usr/local/cuda-11.1/lib64
2023-02-28 13:18:31.312653: W ten

In [2]:
DIMENSIONALITY = 3

In [3]:
model = f3dasm.machinelearning.PassthroughModel(dimensionality=DIMENSIONALITY)
design = f3dasm.make_nd_continuous_design(bounds=np.tile([-1.0,1.0], (DIMENSIONALITY,1)),dimensionality=DIMENSIONALITY)

2023-02-28 13:18:41.177164: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2023-02-28 13:18:41.177273: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (martin): /proc/driver/nvidia/version does not exist
2023-02-28 13:18:41.179154: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
loss_function = f3dasm.functions.Ackley(dimensionality=DIMENSIONALITY, scale_bounds=design.get_bounds())

In [5]:
x = np.array([[0.2]*DIMENSIONALITY])
x.shape

(1, 3)

In [6]:
xx = np.array([[0.2],[0.2]])


In [7]:
loss_function(x)

array([[21.16869004]])

In [8]:
model.get_weights()[0].shape

(3, 1)

In [9]:
model.set_model_weights(x)

In [10]:
x_1 = model(X=x)
x_1

<tf.Tensor: shape=(1, 3), dtype=float64, numpy=array([[0.2, 0.2, 0.2]])>

In [11]:
loss_function = f3dasm.functions.Ackley(dimensionality=DIMENSIONALITY, scale_bounds=design.get_bounds())
f = f3dasm.base.utils.convert_autograd_to_tensorflow(loss_function.__call__)
evaluator = f3dasm.Evaluator(loss_function=f)

In [12]:
y, dxdy = evaluator.evaluate(x)
y, dxdy

(array([[21.16869004]]),
 array([[37.47355768],
        [22.91083065],
        [34.05585207]]))

In [13]:
evaluator.model.trainable_variables

[<tf.Variable 'passthrough_layer_1/Variable:0' shape=(3, 1) dtype=float64, numpy=
 array([[0.2],
        [0.2],
        [0.2]])>]

In [14]:
print(x_1)

tf.Tensor([[0.2 0.2 0.2]], shape=(1, 3), dtype=float64)


In [15]:
f(x_1)

<tf.Tensor: shape=(1, 1), dtype=float64, numpy=array([[21.16869004]])>

In [20]:
a = f3dasm.machinelearning.LinearRegression(dimensionality=DIMENSIONALITY-1)

In [21]:
evaluator2 = f3dasm.Evaluator(loss_function=f, model=f3dasm.machinelearning.LinearRegression(dimensionality=DIMENSIONALITY-1))

In [25]:
a.get_model_weights()

array([[-0.31049442],
       [-1.0322821 ],
       [ 0.        ]], dtype=float32)

In [26]:
a.set_model_weights(x)
a.get_model_weights()

array([[0.2],
       [0.2],
       [0.2]], dtype=float32)

In [30]:
design.get_number_of_input_parameters()

3

In [ ]:
loss_function = f3dasm.functions.Ackley(dimensionality=design.get_number_of_input_parameters(), scale_bounds=design.get_bounds())
f = f3dasm.base.utils.convert_autograd_to_tensorflow(loss_function.__call__)
evaluator = f3dasm.Evaluator(loss_function=f)