In [1]:
import f3dasm
import numpy as np
import tensorflow as tf

2023-02-28 11:57:38.165605: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-28 11:57:38.306643: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-28 11:57:38.919909: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.1/lib64:/usr/local/cuda-11.1/lib64
2023-02-28 11:57:38.919977: W ten

In [2]:
DIMENSIONALITY = 2

In [3]:
model = f3dasm.machinelearning.PassthroughModel(dimensionality=DIMENSIONALITY)
design = f3dasm.make_nd_continuous_design(bounds=np.tile([-1.0,1.0], (DIMENSIONALITY,1)),dimensionality=DIMENSIONALITY)

2023-02-28 11:57:49.353182: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2023-02-28 11:57:49.353304: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (martin): /proc/driver/nvidia/version does not exist
2023-02-28 11:57:49.355061: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
loss_function = f3dasm.functions.Ackley(dimensionality=DIMENSIONALITY, scale_bounds=design.get_bounds())

In [5]:
x = np.array([[0.2]*DIMENSIONALITY])
x.shape

(1, 2)

In [6]:
xx = np.array([[0.2],[0.2]])


In [7]:
loss_function(x)

array([[19.04339904]])

In [8]:
model.get_weights()[0].shape

(2, 1)

In [9]:
model.set_model_weights(x)

In [10]:
x_1 = model(X=x)
x_1

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.2, 0.2]], dtype=float32)>

In [11]:
f = f3dasm.base.utils.convert_autograd_to_tensorflow(loss_function.__call__)

In [12]:
f(x_1)

<tf.Tensor: shape=(1, 1), dtype=float64, numpy=array([[19.04339913]])>

In [14]:
evaluator = f3dasm.Evaluator(loss_function=f)

In [20]:
evaluator.evaluate(x)

TypeError: wrapper() got an unexpected keyword argument 'Y_true'

In [19]:
x_1.shape

TensorShape([1, 2])

In [18]:
x_1

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.2, 0.2]], dtype=float32)>