In [1]:
import numpy as np
from f3dasm.simulation.pybenchfunction import DeckkersAarts, LevyN13, Brown, Sphere, Thevenot, AlpineN1, ThreeHump, Bartels, BukinN6
from f3dasm.simulation.benchmark_functions import Ackley

from f3dasm.base.simulation import Function

# Misschien van waaarde numpy.apply_along_axis

In [2]:
X = np.array([0.1, 0.3]) #input is 1D numpy array
np.apply_along_axis

<function numpy.apply_along_axis(func1d, axis, arr, *args, **kwargs)>

In [3]:
x, y = X

In [4]:
f = Ackley()

In [5]:
xx = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
x = np.array([0.5,0.5])


In [6]:
t = Bartels(seed=42)

In [7]:
x = np.array([0.2,0.1])

t.eval(x)

array([[370001.52505218]])

In [8]:
t.eval(np.array([3.,3.]))

array([[18750001.40995264]])

In [9]:
#t.plot(orientation='3D')

In [10]:
t.input_domain

array([[-500,  500],
       [-500,  500]])

In [11]:
t.input_domain[1,:]

array([-500,  500])

In [12]:
x = np.array([0.,5.])

In [13]:
t.scale_input(x)

array([-500., 4500.])

In [14]:
t.input_domain

array([[-500,  500],
       [-500,  500]])

In [15]:
t.input_domain[:, 0]

array([-500, -500])

In [16]:
import inspect
from f3dasm.simulation import pybenchfunction
available_functions = inspect.getmembers(pybenchfunction, inspect.isclass) #Exclude the baseclass 'Function'
functions = [cls for clsname, cls in available_functions]
for func in functions:
    f = func(dimensionality=2)
    print(f"global min: {f.get_global_minimum(2)}")

    #TODO: FIx if there are more than one global minima

global min: (array([0.5, 0.5]), array([[4.4408921e-16]]))
global min: (array([0.5, 0.5]), array([[-200.]]))
global min: (array([0.51066538, 0.49436323]), array([[-170.077563]]))
WARNING ! Is only is available for d=2
global min: (array([0.47842857, 0.48921429]), array([[-2.59379572]]))
global min: (array([0.33333333, 0.5       ]), array([[0.]]))
global min: (array([0., 0.]), array([[0.]]))
global min: (array([0.7917, 0.7917]), array([[-7.8856007]]))
global min: (array([0.5, 0.5]), array([[1.]]))
global min: (array([0.83333333, 0.55555556]), array([[0.]]))


TypeError: Field elements must be 2- or 3-tuples, got '-1.58214'

In [ ]:
f = BukinN6()
f.get_global_minimum(2)

In [ ]:
f.plot(px=200)

In [ ]:
x = np.array([0.1,0.1])

In [ ]:
f.input_domain

In [ ]:
xx = f.scale_input(x)
xx

In [ ]:
f.descale_input(xx)

In [ ]:
# for _ in range(50):
#     x = np.random.random(size=(2,))
#     print(f"x: {x}, scale: {f.scale_input(x)}, descale {f.descale_input(f.scale_input(x))}")
    
#     #assert all(x == f.descale_input(f.scale_input(x)))

f.get_global_minimum(2)

In [ ]:
x = f.get_global_minimum(2)[0]

In [ ]:
x

In [ ]:
f.eval(x)