In [7]:
import tensorflow as tf
import f3dasm
import numpy as np


In [8]:
t = tf.Variable([-10,1,-2])

In [9]:
tf.clip_by_value(t, clip_value_min=0, clip_value_max=4)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 1, 0], dtype=int32)>

In [18]:
dim = 5
bounds = np.tile([-3.,3.], (dim,1))
design = f3dasm.make_nd_continuous_design(bounds=bounds, dimensionality=dim)
f = f3dasm.functions.Levy(dimensionality=dim, scale_bounds=bounds)
x0 = f3dasm.sampling.RandomUniform(design=design,seed=32).get_samples(1)

In [29]:
ff = f.scale_bounds / 3

In [25]:
f.scale_bounds[:,1]

array([3., 3., 3., 3., 3.])

In [21]:
x = x0.get_n_best_input_parameters_numpy(1)

In [23]:
t = tf.Variable(x)
t

<tf.Variable 'Variable:0' shape=(1, 5) dtype=float64, numpy=array([[ 2.1533356 , -0.76373307,  0.33077267,  2.73393929,  1.42001759]])>

In [31]:
clip_min = ff[:,0]
clip_max = ff[:,1]

tf.clip_by_value(x, clip_value_min=clip_min, clip_value_max=clip_max)

<tf.Tensor: shape=(1, 5), dtype=float64, numpy=array([[ 1.        , -0.76373307,  0.33077267,  1.        ,  1.        ]])>

In [ ]:
constaint= lambda x : tf.clip_by_value(x, clip_value_min=function.scale_bounds[:,0], clip_value_max=function.scale_bounds[:,1])